swagger: '2.0'
info:
  title: Jupyter Notebook API
  description: Notebook API
  version: "5"
  contact:
    name: Jupyter Project
    url: https://jupyter.org
# will be prefixed to all paths
basePath: /api
produces:
  - application/json
consumes:
  - application/json
parameters:
  kernel:
    name: kernel_id
    required: true
    in: path
    description: kernel uuid
    type: string
    format: uuid
  session:
    name: session
    required: true
    in: path
    description: session uuid
    type: string
    format: uuid
  path:
    name: path
    required: true
    in: path
    description: file path
    type: string
  checkpoint_id:
    name: checkpoint_id
    required: true
    in: path
    description: Checkpoint id for a file
    type: string
  section_name:
    name: section_name
    required: true
    in: path
    description: Name of config section
    type: string
  terminal_id:
    name: terminal_id
    required: true
    in: path
    description: ID of terminal session
    type: string

paths:
  /contents/{path}:
    parameters:
      - $ref: '#/parameters/path'
    get:
      summary: Get contents of file or directory
      description: "A client can optionally specify a type and/or format argument via URL parameter. When given, the Contents service shall return a model in the requested type and/or format. If the request cannot be satisfied, e.g. type=text is requested, but the file is binary, then the request shall fail with 400 and have a JSON response containing a 'reason' field, with the value 'bad format' or 'bad type', depending on what was requested."
      tags:
        - contents
      parameters:
        - name: type
          in: query
          description: File type ('file', 'directory')
          type: string
          enum:
            - file
            - directory
        - name: format
          in: query
          description: "How file content should be returned ('text', 'base64')"
          type: string
          enum:
            - text
            - base64
        - name: content
          in: query
          description: "Return content (0 for no content, 1 for return content)"
          type: integer
      responses:
        404:
          description: No item found
        400:
          description: Bad request
          schema:
            type: object
            properties:
              error:
                type: string
                description: Error condition
              reason:
                type: string
                description: Explanation of error reason
        200:
          description: Contents of file or directory
          headers:
            Last-Modified:
              description: Last modified date for file
              type: string
              format: dateTime
          schema:
            $ref: '#/definitions/Contents'
        500:
          description: Model key error